
name: Integration

# Runs on every push to main, and on pull requests to main
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Set up Node JS
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "npm"

      - name: Install Dependencies
        run: npm install

      - name: Run tests
        run: npm test --if-present

      - name: Build app
        run: npm run build

  #Job to create docker image
  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build Docker Image
        run: docker build -f dockerfile -t ${{ secrets.DOCKER_USERNAME }}/react-app-github-action:latest  .
      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/react-app-github-action:latest
# new command added and always provide read and write permission


  # job to push code on ec2
  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ayushad/react-app-github-action:latest
            docker stop my-app || true
            docker rm my-app || true
            docker run -d --name my-app -p 80:5173 ayushad/react-app-github-action:latest


# on:
#   push:
#     branches: [main]
#   pull_request:
#     branches: [main]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Set up Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: 20
#           cache: "npm"

#       - name: Install dependencies
#         run: npm install

#       - name: Run tests
#         run: npm test --if-present

#       - name: Build app
#         run: npm run build
