# Runs on every push to main, and on pull requests to main
name: Integration

# Runs on every push to main, and on pull requests to main
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Set up Node JS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install Dependencies
        run: npm install

      - name: Run tests
        run: npm test --if-present

      - name: Build app
        run: npm run build
# on:
#   push:
#     branches: [main]
#   pull_request:
#     branches: [main]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4
x
#       - name: Set up Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: 20
#           cache: "npm"

#       - name: Install dependencies
#         run: npm install

#       - name: Run tests
#         run: npm test --if-present

#       - name: Build app
#         run: npm run build
